#!bash
#
# AMOEBA
# Addon-Manager (OFBiz ERP) Bash Autocomplete
#
# Copyright 2013 François Lecomte (Néréide)
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

have adm &&
{

_magie()
{
	# Magie (à comprendre et documenter)
	# nécessaire pour une gestion correcte des fichiers/dossiers
	_expand || return 0
	
	_compopt_o_filenames
}

_adm()
{
	local cur prev opts
	
	COMPREPLY=()
	_get_comp_words_by_ref cur prev
	# Raccourcis supprimés : up wa
	opts="aaf add-all-files add-directory add-file af diff help init install l list ll lw list-file new-addon remove-file revert rf seal status uninstall uninstall-all update-file version which-addon"
	
	case $prev in
		# Auto-complétion des commandes de l’ADM
		adm)
			COMPREPLY=( $( compgen -W "$opts" -- "$cur" ) )
			;;
		add-all-files|aaf)
			_magie
			COMPREPLY=( $( compgen -W "-d" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
		add-directory)
			_magie
			COMPREPLY=( $( compgen -W "-f -size" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
		add-file|af)
			_magie
			COMPREPLY=( $( compgen -W "-d -f -size" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
		diff)
			_magie
			COMPREPLY=( $( compgen -W "* -all -index -r -size" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
		help)
			COMPREPLY=( $( compgen -W "$opts" -- "$cur" ) )
			;;
		init)
			COMPREPLY=( $( compgen -W "-branch -filter -repository" -- "$cur" ) )
			;;
		install)
			_magie
			COMPREPLY=( $( compgen -W "--force-all --force-depen --force-ivy-tree --force-patch -org -v" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
		list|l)
			COMPREPLY=( $( compgen -W "-head -m -tree -work -works" -- "$cur" ) )
			;;
		ll|lw)
			COMPREPLY=( $( compgen -W " -m -tree" -- "$cur" ) )
			;;
		# À replacer par du code utile (base : `adm list` | grep )
		list-file)
			return 0
			;;
		# À améliorer (base : `adm list` | grep )
		new-addon)
			_magie
			COMPREPLY=( $( compgen -W "-d" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
		remove-file|rf)
			_magie
			COMPREPLY=( $( compgen -f -- "$cur" ) )
			;;
		revert)
			_magie
			COMPREPLY=( $( compgen -W "-all -r" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
		seal)
			COMPREPLY=( $( compgen -W "-revision" -- "$cur" ))
			;;
		status)
			COMPREPLY=( $( compgen -W "-detail" -- "$cur" ))
			;;
		# À améliorer (base : `adm list` | grep )
		uninstall)
			COMPREPLY=( $( compgen -W "--force-revert --no-reload" -- "$cur" ) )
			;;
		uninstall-all)
			COMPREPLY=( $( compgen -W "--force-revert" -- "$cur" ))
			;;
		update-file|up)
			_magie
			COMPREPLY=( $( compgen -W "-d -size" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
		version)
			return 0
			;;
        which-addon|wa)
			_magie
			COMPREPLY=( $( compgen -W "-detail" -- "$cur" ) \
			$( compgen -f -- "$cur" ) )
			;;
        # Auto-complétion par défaut
        *)
            _magie
            COMPREPLY=( $( compgen -f -- "$cur" ) )   
            ;;
	esac
	
	return 0
} &&
complete -F _adm adm

}
